import { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    dir: 'ltr',
    flag: '🇬🇧',
    label: 'EN',
    nav: {
      home: 'Home',
      offers: 'Offers',
      quads: 'Our Quads',
      gallery: 'Gallery',
      bookNow: 'Book Now',
    },
    products: {
      sectionTag: 'Our Fleet',
      sectionTitle: 'Choose Your Quad',
      subtitle: 'Premium machines for every rider — beginner to expert. All quads fully maintained and equipped with safety gear.',
      specs: 'Specs',
      bookThis: 'Book This Quad',
      items: [
        {
          name: 'Quad 110cc — Enfant',
          engine: '110cc',
          type: 'Automatique',
          seats: '1',
          forWho: 'Enfants 6–12 ans',
          price: '80 MAD/h',
          image: 'https://images.pexels.com/photos/163210/motorcycles-race-speed-helmet-163210.jpeg?w=600',
          tag: 'Junior',
          color: '#FFB800',
        },
        {
          name: 'Quad 150cc — Adulte',
          engine: '150cc',
          type: 'Manuel',
          seats: '1',
          forWho: 'Adultes débutants',
          price: '150 MAD/h',
          image: 'https://images.pexels.com/photos/1007410/pexels-photo-1007410.jpeg?w=600',
          tag: 'Populaire',
          color: '#FF5C00',
        },
        {
          name: 'Quad 250cc — Sport',
          engine: '250cc',
          type: 'Manuel',
          seats: '1',
          forWho: 'Riders expérimentés',
          price: '200 MAD/h',
          image: 'https://images.pexels.com/photos/35967/mini-cooper-auto-model-vehicle.jpg?w=600',
          tag: 'Sport',
          color: '#FF8A00',
        },
        {
          name: 'Buggy 500cc — Duo',
          engine: '500cc',
          type: 'Automatique',
          seats: '2',
          forWho: 'Couples & amis',
          price: '350 MAD/h',
          image: 'https://images.pexels.com/photos/1402787/pexels-photo-1402787.jpeg?w=600',
          tag: 'Duo',
          color: '#FF5C00',
        },
        {
          name: 'Quad 400cc — Expert',
          engine: '400cc',
          type: 'Manuel',
          seats: '1',
          forWho: 'Experts & groupes',
          price: '280 MAD/h',
          image: 'https://images.pexels.com/photos/1118448/pexels-photo-1118448.jpeg?w=600',
          tag: 'Expert',
          color: '#FF8A00',
        },
        {
          name: 'Buggy 800cc — Famille',
          engine: '800cc',
          type: 'Automatique',
          seats: '4',
          forWho: 'Familles & groupes',
          price: '500 MAD/h',
          image: 'https://images.pexels.com/photos/2611686/pexels-photo-2611686.jpeg?w=600',
          tag: 'Famille',
          color: '#FFB800',
        },
      ],
    },
    hero: {
      location: 'Tetouan, Morocco',
      title1: 'Dominate',
      titleAccent: 'Every',
      title2: 'Trail',
      subtitle: '30 premium quads. Expert guides. Epic trails in the mountains of Northern Morocco.',
      cta1: 'Book Now',
      cta2: 'Our Quads',
      scroll: 'Scroll',
      badge: '200+ Riders',
      stat1: '30 Quads Available',
      stat2: 'Full Safety Gear',
      stat3: 'Tetouan Mountains',
    },
    stats: {
      quads: 'Quads',
      riders: 'Happy Riders',
      trails: 'Scenic Trails',
      years: 'Years of Adventure',
    },
    features: {
      sectionTag: 'Why Choose Us',
      sectionTitle: 'Built for Adventure',
      items: [
        { title: '30 Modern Quads', desc: 'Full fleet, all sizes, always maintained to the highest standard.' },
        { title: 'Expert Local Guides', desc: 'Know every trail, river crossing and hidden gem in the region.' },
        { title: 'Safety First', desc: 'Helmets, full protective gear and thorough briefing included.' },
        { title: 'Scenic Trails', desc: 'Mountains, rivers and coastal routes — pure northern Morocco.' },
      ],
    },
    offers: {
      sectionTag: 'Our Packages',
      sectionTitle: 'Choose Your Ride',
      subtitle: 'From a quick thrill to a full-day epic — we have the perfect package for you.',
      bookNow: 'Book Now',
      from: 'From',
      popular: 'Most Popular',
      packages: [
        { title: 'Express Ride', duration: '2 hours', price: '250 MAD', desc: 'Perfect intro ride through scenic Tetouan trails. Great for first-timers.' },
        { title: 'Half-Day Adventure', duration: '4–5 hours', price: '450 MAD', desc: 'Deep trails, mountain views, and a local lunch stop included.' },
        { title: 'Group Package', duration: 'Full day', price: '350 MAD/person', desc: 'Ideal for 8+ people. Custom route, BBQ and photos included.' },
      ],
    },
    gallery: {
      sectionTag: 'Moments on Trail',
      sectionTitle: 'Gallery',
      followBtn: 'Follow us on Instagram',
    },
    testimonials: {
      sectionTag: 'Rider Reviews',
      sectionTitle: 'What They Say',
      items: [
        { quote: 'Best experience in Morocco! The guides were amazing and the trail through the mountains was breathtaking.', name: 'Sarah M.', flag: '🇬🇧' },
        { quote: 'Les quads étaient en parfait état! Organisation impeccable et guides très professionnels. Je recommande!', name: 'Karim B.', flag: '🇫🇷' },
        { quote: 'Amazing guides, incredible trails! We did the half-day adventure and it was worth every dirham.', name: 'Ahmed R.', flag: '🇲🇦' },
        { quote: 'Totally worth it, booked twice already! Once solo, once with my family. GoQuad never disappoints.', name: 'Emma L.', flag: '🇩🇪' },
        { quote: 'Perfect group activity! We had 15 people and they handled everything flawlessly. The BBQ was a bonus.', name: 'Youssef T.', flag: '🇲🇦' },
      ],
    },
    cta: {
      title1: '30 Quads.',
      title2: 'Zero Regrets.',
      subtitle: 'Book your slot now before it fills up.',
      btn: 'Book Now',
    },
    booking: {
      sectionTag: 'Reserve Your Spot',
      sectionTitle: 'Book Your Ride',
      subtitle: "Fill in the form below and we'll confirm your booking via WhatsApp.",
      service: 'Service',
      selectPackage: 'Select a package',
      date: 'Date',
      time: 'Time',
      selectTime: 'Select time',
      people: 'Number of People',
      name: 'Full Name',
      namePlaceholder: 'Your full name',
      phone: 'Phone',
      phonePlaceholder: '+212 6XX XXXXXX',
      email: 'Email',
      specialRequests: 'Special Requests',
      optional: '(optional)',
      specialPlaceholder: 'Any special requirements, accessibility needs, etc.',
      submit: 'Confirm Booking →',
      submitting: 'Processing...',
      waNote: "📱 You'll receive a WhatsApp confirmation within 15 min",
      successTitle: 'Booking Confirmed!',
      successDesc: "We'll WhatsApp you shortly with your booking details and meetup point.",
      successTagline: 'See you on the trail! 🏍️',
      close: 'Close',
      slotFull: 'This slot is full. Please choose another time.',
      errors: {
        service: 'Please select a service',
        date: 'Please select a date',
        time: 'Please select a time',
        peopleRequired: 'Required',
        peopleMin: 'At least 1 person',
        peopleMax: 'Max 30 people per booking',
        name: 'Name is required',
        phone: 'Phone is required',
        email: 'Email is required',
        emailInvalid: 'Invalid email',
      },
    },
    map: {
      sectionTag: 'Location',
      sectionTitle: 'Find Us in Tetouan',
      getInTouch: 'Get in Touch',
      phone: 'Phone',
      whatsapp: 'WhatsApp',
      whatsappValue: 'Chat with us',
      email: 'Email',
      address: 'Address',
      addressValue: 'Tetouan, Northern Morocco',
      hours: 'Opening Hours',
      days: 'Monday – Sunday',
    },
    footer: {
      tagline: 'Premium quad bike rentals and adventure tours in Tetouan, Morocco. 30 quads. Expert guides. Unforgettable trails.',
      navigation: 'Navigation',
      followUs: 'Follow Us',
      copyright: '© 2026 GoQuad Tetouan. All rights reserved.',
      madeWith: 'Made with ❤️ in Tetouan, Morocco',
    },
  },

  fr: {
    dir: 'ltr',
    flag: '🇫🇷',
    label: 'FR',
    nav: {
      home: 'Accueil',
      offers: 'Offres',
      quads: 'Nos Quads',
      gallery: 'Galerie',
      bookNow: 'Réserver',
    },
    products: {
      sectionTag: 'Notre Flotte',
      sectionTitle: 'Choisissez Votre Quad',
      subtitle: 'Des machines premium pour tous les niveaux — débutant à expert. Tous nos quads sont entretenus et équipés.',
      specs: 'Caractéristiques',
      bookThis: 'Réserver ce Quad',
      items: [
        { name: 'Quad 110cc — Enfant', engine: '110cc', type: 'Automatique', seats: '1', forWho: 'Enfants 6–12 ans', price: '80 MAD/h', image: 'https://images.pexels.com/photos/163210/motorcycles-race-speed-helmet-163210.jpeg?w=600', tag: 'Junior', color: '#FFB800' },
        { name: 'Quad 150cc — Adulte', engine: '150cc', type: 'Manuel', seats: '1', forWho: 'Adultes débutants', price: '150 MAD/h', image: 'https://images.pexels.com/photos/1007410/pexels-photo-1007410.jpeg?w=600', tag: 'Populaire', color: '#FF5C00' },
        { name: 'Quad 250cc — Sport', engine: '250cc', type: 'Manuel', seats: '1', forWho: 'Riders expérimentés', price: '200 MAD/h', image: 'https://images.pexels.com/photos/35967/mini-cooper-auto-model-vehicle.jpg?w=600', tag: 'Sport', color: '#FF8A00' },
        { name: 'Buggy 500cc — Duo', engine: '500cc', type: 'Automatique', seats: '2', forWho: 'Couples & amis', price: '350 MAD/h', image: 'https://images.pexels.com/photos/1402787/pexels-photo-1402787.jpeg?w=600', tag: 'Duo', color: '#FF5C00' },
        { name: 'Quad 400cc — Expert', engine: '400cc', type: 'Manuel', seats: '1', forWho: 'Experts & groupes', price: '280 MAD/h', image: 'https://images.pexels.com/photos/1118448/pexels-photo-1118448.jpeg?w=600', tag: 'Expert', color: '#FF8A00' },
        { name: 'Buggy 800cc — Famille', engine: '800cc', type: 'Automatique', seats: '4', forWho: 'Familles & groupes', price: '500 MAD/h', image: 'https://images.pexels.com/photos/2611686/pexels-photo-2611686.jpeg?w=600', tag: 'Famille', color: '#FFB800' },
      ],
    },
    hero: {
      location: 'Tétouan, Maroc',
      title1: 'Dominez',
      titleAccent: 'Chaque',
      title2: 'Piste',
      subtitle: '30 quads premium. Guides experts. Des pistes épiques dans les montagnes du Maroc du Nord.',
      cta1: 'Réserver',
      cta2: 'Nos Quads',
      scroll: 'Défiler',
      badge: '200+ Pilotes',
      stat1: '30 Quads Disponibles',
      stat2: 'Équipement Complet',
      stat3: 'Montagnes de Tétouan',
    },
    stats: {
      quads: 'Quads',
      riders: 'Riders Satisfaits',
      trails: 'Pistes Panoramiques',
      years: "Années d'Aventure",
    },
    features: {
      sectionTag: 'Pourquoi Nous Choisir',
      sectionTitle: "Fait pour l'Aventure",
      items: [
        { title: '30 Quads Modernes', desc: 'Flotte complète, toutes tailles, toujours entretenue au plus haut niveau.' },
        { title: 'Guides Locaux Experts', desc: 'Connaissent chaque piste, gué et joyau caché de la région.' },
        { title: 'Sécurité Avant Tout', desc: 'Casques, équipement complet et briefing inclus.' },
        { title: 'Pistes Panoramiques', desc: 'Montagnes, rivières et côtes — le vrai Maroc du Nord.' },
      ],
    },
    offers: {
      sectionTag: 'Nos Forfaits',
      sectionTitle: 'Choisissez Votre Ride',
      subtitle: "Du frisson rapide à l'épopée d'une journée — le forfait parfait existe.",
      bookNow: 'Réserver',
      from: 'À partir de',
      popular: 'Le Plus Populaire',
      packages: [
        { title: 'Balade Express', duration: '2 heures', price: '250 MAD', desc: "Intro parfaite sur les pistes pittoresques de Tétouan. Idéal pour les débutants." },
        { title: "Aventure Demi-Journée", duration: '4–5 heures', price: '450 MAD', desc: 'Pistes profondes, vues sur la montagne et arrêt déjeuner local.' },
        { title: 'Forfait Groupe', duration: 'Journée complète', price: '350 MAD/pers.', desc: 'Idéal pour 8+ personnes. Itinéraire personnalisé, BBQ et photos inclus.' },
      ],
    },
    gallery: {
      sectionTag: 'Moments en Piste',
      sectionTitle: 'Galerie',
      followBtn: 'Nous suivre sur Instagram',
    },
    testimonials: {
      sectionTag: 'Avis des Pilotes',
      sectionTitle: "Ce Qu'ils Disent",
      items: [
        { quote: 'Meilleure expérience au Maroc! Les guides étaient incroyables et la piste en montagne époustouflante.', name: 'Sarah M.', flag: '🇬🇧' },
        { quote: 'Les quads étaient en parfait état! Organisation impeccable et guides très professionnels. Je recommande!', name: 'Karim B.', flag: '🇫🇷' },
        { quote: 'Guides fantastiques, pistes incroyables! On a fait la demi-journée, chaque dirham en valait la peine.', name: 'Ahmed R.', flag: '🇲🇦' },
        { quote: "Ça vaut totalement le coup, j'ai réservé deux fois! En solo puis en famille. GoQuad ne déçoit jamais.", name: 'Emma L.', flag: '🇩🇪' },
        { quote: "Activité de groupe parfaite! 15 personnes et tout s'est passé à merveille. Le BBQ était un bonus.", name: 'Youssef T.', flag: '🇲🇦' },
      ],
    },
    cta: {
      title1: '30 Quads.',
      title2: 'Zéro Regret.',
      subtitle: "Réservez votre créneau avant qu'il soit plein.",
      btn: 'Réserver',
    },
    booking: {
      sectionTag: 'Réservez Votre Place',
      sectionTitle: 'Réserver Votre Ride',
      subtitle: "Remplissez le formulaire et nous confirmerons votre réservation par WhatsApp.",
      service: 'Service',
      selectPackage: 'Choisissez un forfait',
      date: 'Date',
      time: 'Heure',
      selectTime: "Choisissez l'heure",
      people: 'Nombre de personnes',
      name: 'Nom complet',
      namePlaceholder: 'Votre nom complet',
      phone: 'Téléphone',
      phonePlaceholder: '+212 6XX XXXXXX',
      email: 'E-mail',
      specialRequests: 'Demandes spéciales',
      optional: '(optionnel)',
      specialPlaceholder: 'Besoins particuliers, accessibilité, etc.',
      submit: 'Confirmer la Réservation →',
      submitting: 'Traitement...',
      waNote: '📱 Vous recevrez une confirmation WhatsApp dans les 15 min',
      successTitle: 'Réservation Confirmée!',
      successDesc: 'Nous vous contacterons sur WhatsApp avec les détails et le point de rendez-vous.',
      successTagline: 'À bientôt sur la piste! 🏍️',
      close: 'Fermer',
      slotFull: 'Ce créneau est complet. Veuillez choisir un autre horaire.',
      errors: {
        service: 'Veuillez sélectionner un service',
        date: 'Veuillez sélectionner une date',
        time: 'Veuillez sélectionner une heure',
        peopleRequired: 'Requis',
        peopleMin: 'Au moins 1 personne',
        peopleMax: '30 personnes maximum',
        name: 'Le nom est requis',
        phone: 'Le téléphone est requis',
        email: "L'e-mail est requis",
        emailInvalid: 'E-mail invalide',
      },
    },
    map: {
      sectionTag: 'Localisation',
      sectionTitle: 'Trouvez-Nous à Tétouan',
      getInTouch: 'Contactez-Nous',
      phone: 'Téléphone',
      whatsapp: 'WhatsApp',
      whatsappValue: 'Discutez avec nous',
      email: 'E-mail',
      address: 'Adresse',
      addressValue: 'Tétouan, Maroc du Nord',
      hours: "Heures d'ouverture",
      days: 'Lundi – Dimanche',
    },
    footer: {
      tagline: 'Location de quads premium et circuits aventure à Tétouan, Maroc. 30 quads. Guides experts. Pistes inoubliables.',
      navigation: 'Navigation',
      followUs: 'Suivez-Nous',
      copyright: '© 2026 GoQuad Tetouan. Tous droits réservés.',
      madeWith: 'Fait avec ❤️ à Tétouan, Maroc',
    },
  },

  ar: {
    dir: 'rtl',
    flag: '🇲🇦',
    label: 'AR',
    nav: {
      home: 'الرئيسية',
      offers: 'العروض',
      quads: 'كواداتنا',
      gallery: 'المعرض',
      bookNow: 'احجز الآن',
    },
    products: {
      sectionTag: 'أسطولنا',
      sectionTitle: 'اختر كوادك',
      subtitle: 'آلات فاخرة لكل مستوى — من المبتدئ إلى الخبير. جميع كواداتنا مصانة ومجهزة بالكامل.',
      specs: 'المواصفات',
      bookThis: 'احجز هذا الكواد',
      items: [
        { name: 'كواد 110cc — أطفال', engine: '110cc', type: 'أوتوماتيك', seats: '1', forWho: 'أطفال 6–12 سنة', price: '80 درهم/س', image: 'https://images.pexels.com/photos/163210/motorcycles-race-speed-helmet-163210.jpeg?w=600', tag: 'جونيور', color: '#FFB800' },
        { name: 'كواد 150cc — بالغ', engine: '150cc', type: 'يدوي', seats: '1', forWho: 'مبتدئون بالغون', price: '150 درهم/س', image: 'https://images.pexels.com/photos/1007410/pexels-photo-1007410.jpeg?w=600', tag: 'الأكثر شعبية', color: '#FF5C00' },
        { name: 'كواد 250cc — رياضي', engine: '250cc', type: 'يدوي', seats: '1', forWho: 'راكبون متمرسون', price: '200 درهم/س', image: 'https://images.pexels.com/photos/35967/mini-cooper-auto-model-vehicle.jpg?w=600', tag: 'رياضي', color: '#FF8A00' },
        { name: 'باغي 500cc — ثنائي', engine: '500cc', type: 'أوتوماتيك', seats: '2', forWho: 'أزواج وأصدقاء', price: '350 درهم/س', image: 'https://images.pexels.com/photos/1402787/pexels-photo-1402787.jpeg?w=600', tag: 'ثنائي', color: '#FF5C00' },
        { name: 'كواد 400cc — خبير', engine: '400cc', type: 'يدوي', seats: '1', forWho: 'خبراء ومجموعات', price: '280 درهم/س', image: 'https://images.pexels.com/photos/1118448/pexels-photo-1118448.jpeg?w=600', tag: 'خبير', color: '#FF8A00' },
        { name: 'باغي 800cc — عائلة', engine: '800cc', type: 'أوتوماتيك', seats: '4', forWho: 'عائلات ومجموعات', price: '500 درهم/س', image: 'https://images.pexels.com/photos/2611686/pexels-photo-2611686.jpeg?w=600', tag: 'عائلة', color: '#FFB800' },
      ],
    },
    hero: {
      location: 'تطوان، المغرب',
      title1: 'تحكم في',
      titleAccent: 'كل',
      title2: 'مسار',
      subtitle: '٣٠ كواد فاخر. مرشدون خبراء. مسالك ملحمية في جبال شمال المغرب.',
      cta1: 'احجز الآن',
      cta2: 'كواداتنا',
      scroll: 'تمرير',
      badge: '+٢٠٠ راكب',
      stat1: '٣٠ كواد متاح',
      stat2: 'معدات سلامة كاملة',
      stat3: 'جبال تطوان',
    },
    stats: {
      quads: 'كواد',
      riders: 'راكب سعيد',
      trails: 'مسار طبيعي',
      years: 'سنوات من المغامرة',
    },
    features: {
      sectionTag: 'لماذا تختارنا',
      sectionTitle: 'صُنع للمغامرة',
      items: [
        { title: '٣٠ كواد حديث', desc: 'أسطول كامل بجميع الأحجام، دائم الصيانة على أعلى مستوى.' },
        { title: 'مرشدون محليون خبراء', desc: 'يعرفون كل مسار وعبور ونهر وكنز خفي في المنطقة.' },
        { title: 'السلامة أولاً', desc: 'خوذات ومعدات واقية كاملة وإحاطة شاملة مشمولة.' },
        { title: 'مسالك خلابة', desc: 'جبال وأنهار ومسارات ساحلية — شمال المغرب الأصيل.' },
      ],
    },
    offers: {
      sectionTag: 'باقاتنا',
      sectionTitle: 'اختر رحلتك',
      subtitle: 'من الإثارة السريعة إلى مغامرة يوم كامل — لدينا الباقة المثالية لك.',
      bookNow: 'احجز الآن',
      from: 'ابتداءً من',
      popular: 'الأكثر شعبية',
      packages: [
        { title: 'جولة سريعة', duration: 'ساعتان', price: '٢٥٠ درهم', desc: 'مقدمة مثالية في مسالك تطوان الخلابة. مثالية للمبتدئين.' },
        { title: 'مغامرة نصف يوم', duration: '٤–٥ ساعات', price: '٤٥٠ درهم', desc: 'مسالك عميقة ومناظر جبلية وتوقف لتناول غداء محلي.' },
        { title: 'باقة المجموعة', duration: 'يوم كامل', price: '٣٥٠ درهم/شخص', desc: 'مثالية لـ٨ أشخاص فأكثر. مسار مخصص وشواء وصور مشمولة.' },
      ],
    },
    gallery: {
      sectionTag: 'لحظات على المسار',
      sectionTitle: 'المعرض',
      followBtn: 'تابعنا على إنستغرام',
    },
    testimonials: {
      sectionTag: 'آراء الركاب',
      sectionTitle: 'ماذا يقولون',
      items: [
        { quote: 'أفضل تجربة في المغرب! المرشدون كانوا رائعين والمسار الجبلي كان مذهلاً.', name: 'سارة م.', flag: '🇬🇧' },
        { quote: 'الكوادات كانت في حالة ممتازة! تنظيم لا تشوبه شائبة ومرشدون محترفون جداً.', name: 'كريم ب.', flag: '🇫🇷' },
        { quote: 'مرشدون مذهلون ومسالك رائعة! قمنا بمغامرة نصف يوم وكانت تستحق كل درهم.', name: 'أحمد ر.', flag: '🇲🇦' },
        { quote: 'يستحق ذلك تماماً، حجزت مرتين! مرة منفرداً ومرة مع عائلتي. GoQuad لا تخذل أبداً.', name: 'إيما ل.', flag: '🇩🇪' },
        { quote: 'نشاط جماعي مثالي! كنا ١٥ شخصاً وأداروا كل شيء بسلاسة تامة. الشواء كان مكافأة!', name: 'يوسف ت.', flag: '🇲🇦' },
      ],
    },
    cta: {
      title1: '٣٠ كواد.',
      title2: 'صفر ندم.',
      subtitle: 'احجز مكانك الآن قبل أن ينتهي.',
      btn: 'احجز الآن',
    },
    booking: {
      sectionTag: 'احجز مكانك',
      sectionTitle: 'احجز رحلتك',
      subtitle: 'املأ النموذج أدناه وسنؤكد حجزك عبر واتساب.',
      service: 'الخدمة',
      selectPackage: 'اختر باقة',
      date: 'التاريخ',
      time: 'الوقت',
      selectTime: 'اختر الوقت',
      people: 'عدد الأشخاص',
      name: 'الاسم الكامل',
      namePlaceholder: 'اسمك الكامل',
      phone: 'الهاتف',
      phonePlaceholder: '+212 6XX XXXXXX',
      email: 'البريد الإلكتروني',
      specialRequests: 'طلبات خاصة',
      optional: '(اختياري)',
      specialPlaceholder: 'أي متطلبات خاصة أو احتياجات وصول، إلخ.',
      submit: 'تأكيد الحجز ←',
      submitting: 'جارٍ المعالجة...',
      waNote: '📱 ستتلقى تأكيداً عبر واتساب في غضون ١٥ دقيقة',
      successTitle: 'تم تأكيد الحجز!',
      successDesc: 'سنتواصل معك عبر واتساب بتفاصيل حجزك ونقطة اللقاء.',
      successTagline: 'نراك على المسار! 🏍️',
      close: 'إغلاق',
      slotFull: 'هذا الموعد ممتلئ. يرجى اختيار وقت آخر.',
      errors: {
        service: 'الرجاء اختيار خدمة',
        date: 'الرجاء اختيار تاريخ',
        time: 'الرجاء اختيار وقت',
        peopleRequired: 'مطلوب',
        peopleMin: 'شخص واحد على الأقل',
        peopleMax: '٣٠ شخصاً كحد أقصى',
        name: 'الاسم مطلوب',
        phone: 'الهاتف مطلوب',
        email: 'البريد الإلكتروني مطلوب',
        emailInvalid: 'بريد إلكتروني غير صالح',
      },
    },
    map: {
      sectionTag: 'الموقع',
      sectionTitle: 'جدنا في تطوان',
      getInTouch: 'تواصل معنا',
      phone: 'الهاتف',
      whatsapp: 'واتساب',
      whatsappValue: 'تحدث معنا',
      email: 'البريد الإلكتروني',
      address: 'العنوان',
      addressValue: 'تطوان، شمال المغرب',
      hours: 'ساعات العمل',
      days: 'الاثنين – الأحد',
    },
    footer: {
      tagline: 'تأجير كوادات فاخرة وجولات مغامرة في تطوان، المغرب. ٣٠ كواد. مرشدون خبراء. مسالك لا تُنسى.',
      navigation: 'التنقل',
      followUs: 'تابعنا',
      copyright: '© ٢٠٢٦ GoQuad تطوان. جميع الحقوق محفوظة.',
      madeWith: 'صُنع بـ ❤️ في تطوان، المغرب',
    },
  },

  es: {
    dir: 'ltr',
    flag: '🇪🇸',
    label: 'ES',
    nav: {
      home: 'Inicio',
      offers: 'Ofertas',
      quads: 'Nuestros Quads',
      gallery: 'Galería',
      bookNow: 'Reservar',
    },
    products: {
      sectionTag: 'Nuestra Flota',
      sectionTitle: 'Elige Tu Quad',
      subtitle: 'Máquinas premium para todo nivel — principiante a experto. Todos nuestros quads están mantenidos y equipados.',
      specs: 'Características',
      bookThis: 'Reservar este Quad',
      items: [
        { name: 'Quad 110cc — Niños', engine: '110cc', type: 'Automático', seats: '1', forWho: 'Niños 6–12 años', price: '80 MAD/h', image: 'https://images.pexels.com/photos/163210/motorcycles-race-speed-helmet-163210.jpeg?w=600', tag: 'Junior', color: '#FFB800' },
        { name: 'Quad 150cc — Adulto', engine: '150cc', type: 'Manual', seats: '1', forWho: 'Adultos principiantes', price: '150 MAD/h', image: 'https://images.pexels.com/photos/1007410/pexels-photo-1007410.jpeg?w=600', tag: 'Popular', color: '#FF5C00' },
        { name: 'Quad 250cc — Sport', engine: '250cc', type: 'Manual', seats: '1', forWho: 'Riders experimentados', price: '200 MAD/h', image: 'https://images.pexels.com/photos/35967/mini-cooper-auto-model-vehicle.jpg?w=600', tag: 'Sport', color: '#FF8A00' },
        { name: 'Buggy 500cc — Dúo', engine: '500cc', type: 'Automático', seats: '2', forWho: 'Parejas y amigos', price: '350 MAD/h', image: 'https://images.pexels.com/photos/1402787/pexels-photo-1402787.jpeg?w=600', tag: 'Dúo', color: '#FF5C00' },
        { name: 'Quad 400cc — Experto', engine: '400cc', type: 'Manual', seats: '1', forWho: 'Expertos y grupos', price: '280 MAD/h', image: 'https://images.pexels.com/photos/1118448/pexels-photo-1118448.jpeg?w=600', tag: 'Experto', color: '#FF8A00' },
        { name: 'Buggy 800cc — Familia', engine: '800cc', type: 'Automático', seats: '4', forWho: 'Familias y grupos', price: '500 MAD/h', image: 'https://images.pexels.com/photos/2611686/pexels-photo-2611686.jpeg?w=600', tag: 'Familia', color: '#FFB800' },
      ],
    },
    hero: {
      location: 'Tetuán, Marruecos',
      title1: 'Domina',
      titleAccent: 'Cada',
      title2: 'Ruta',
      subtitle: '30 quads premium. Guías expertos. Rutas épicas en las montañas del norte de Marruecos.',
      cta1: 'Reservar Ahora',
      cta2: 'Nuestros Quads',
      scroll: 'Desplazar',
      badge: '200+ Pilotos',
      stat1: '30 Quads Disponibles',
      stat2: 'Equipo Completo',
      stat3: 'Montañas de Tetuán',
    },
    stats: {
      quads: 'Quads',
      riders: 'Pilotos Felices',
      trails: 'Rutas Panorámicas',
      years: 'Años de Aventura',
    },
    features: {
      sectionTag: '¿Por Qué Elegirnos?',
      sectionTitle: 'Hecho para la Aventura',
      items: [
        { title: '30 Quads Modernos', desc: 'Flota completa, todos los tamaños, siempre en perfecto mantenimiento.' },
        { title: 'Guías Locales Expertos', desc: 'Conocen cada ruta, vadeo y joya oculta de la región.' },
        { title: 'Seguridad Ante Todo', desc: 'Cascos, equipo completo y briefing exhaustivo incluidos.' },
        { title: 'Rutas Panorámicas', desc: 'Montañas, ríos y rutas costeras — el Marruecos del norte auténtico.' },
      ],
    },
    offers: {
      sectionTag: 'Nuestros Paquetes',
      sectionTitle: 'Elige tu Ruta',
      subtitle: 'Desde una emoción rápida hasta una épica de día completo — tenemos el paquete perfecto para ti.',
      bookNow: 'Reservar',
      from: 'Desde',
      popular: 'El Más Popular',
      packages: [
        { title: 'Ruta Exprés', duration: '2 horas', price: '250 MAD', desc: 'Introducción perfecta por las pintorescas rutas de Tetuán. Ideal para principiantes.' },
        { title: 'Aventura Media Jornada', duration: '4–5 horas', price: '450 MAD', desc: 'Rutas profundas, vistas a la montaña y parada para almorzar localmente.' },
        { title: 'Paquete Grupal', duration: 'Día completo', price: '350 MAD/persona', desc: 'Ideal para 8+ personas. Ruta personalizada, BBQ y fotos incluidos.' },
      ],
    },
    gallery: {
      sectionTag: 'Momentos en Ruta',
      sectionTitle: 'Galería',
      followBtn: 'Síguenos en Instagram',
    },
    testimonials: {
      sectionTag: 'Reseñas de Pilotos',
      sectionTitle: '¿Qué Dicen?',
      items: [
        { quote: '¡La mejor experiencia en Marruecos! Los guías fueron increíbles y la ruta por la montaña, impresionante.', name: 'Sarah M.', flag: '🇬🇧' },
        { quote: '¡Los quads estaban en perfecto estado! Organización impecable y guías muy profesionales. ¡Lo recomiendo!', name: 'Karim B.', flag: '🇫🇷' },
        { quote: '¡Guías increíbles, rutas espectaculares! Hicimos la media jornada y valió cada dírham.', name: 'Ahmed R.', flag: '🇲🇦' },
        { quote: '¡Totalmente vale la pena, ya reservé dos veces! Solo y luego con mi familia. GoQuad nunca defrauda.', name: 'Emma L.', flag: '🇩🇪' },
        { quote: '¡Actividad grupal perfecta! Éramos 15 personas y lo gestionaron todo a la perfección. El BBQ fue un bonus.', name: 'Youssef T.', flag: '🇲🇦' },
      ],
    },
    cta: {
      title1: '30 Quads.',
      title2: 'Cero Arrepentimientos.',
      subtitle: 'Reserva tu plaza ahora antes de que se llene.',
      btn: 'Reservar',
    },
    booking: {
      sectionTag: 'Reserva tu Plaza',
      sectionTitle: 'Reserva tu Ruta',
      subtitle: 'Rellena el formulario y confirmaremos tu reserva por WhatsApp.',
      service: 'Servicio',
      selectPackage: 'Elige un paquete',
      date: 'Fecha',
      time: 'Hora',
      selectTime: 'Elige la hora',
      people: 'Número de personas',
      name: 'Nombre completo',
      namePlaceholder: 'Tu nombre completo',
      phone: 'Teléfono',
      phonePlaceholder: '+212 6XX XXXXXX',
      email: 'Correo electrónico',
      specialRequests: 'Peticiones especiales',
      optional: '(opcional)',
      specialPlaceholder: 'Requisitos especiales, necesidades de accesibilidad, etc.',
      submit: 'Confirmar Reserva →',
      submitting: 'Procesando...',
      waNote: '📱 Recibirás una confirmación de WhatsApp en 15 min',
      successTitle: '¡Reserva Confirmada!',
      successDesc: 'Te contactaremos por WhatsApp con los detalles de tu reserva y punto de encuentro.',
      successTagline: '¡Nos vemos en la ruta! 🏍️',
      close: 'Cerrar',
      slotFull: 'Este horario está lleno. Por favor elige otro.',
      errors: {
        service: 'Por favor selecciona un servicio',
        date: 'Por favor selecciona una fecha',
        time: 'Por favor selecciona una hora',
        peopleRequired: 'Requerido',
        peopleMin: 'Mínimo 1 persona',
        peopleMax: 'Máximo 30 personas',
        name: 'El nombre es obligatorio',
        phone: 'El teléfono es obligatorio',
        email: 'El correo es obligatorio',
        emailInvalid: 'Correo no válido',
      },
    },
    map: {
      sectionTag: 'Ubicación',
      sectionTitle: 'Encuéntranos en Tetuán',
      getInTouch: 'Contáctanos',
      phone: 'Teléfono',
      whatsapp: 'WhatsApp',
      whatsappValue: 'Chatea con nosotros',
      email: 'Correo',
      address: 'Dirección',
      addressValue: 'Tetuán, Norte de Marruecos',
      hours: 'Horario',
      days: 'Lunes – Domingo',
    },
    footer: {
      tagline: 'Alquiler premium de quads y tours de aventura en Tetuán, Marruecos. 30 quads. Guías expertos. Rutas inolvidables.',
      navigation: 'Navegación',
      followUs: 'Síguenos',
      copyright: '© 2026 GoQuad Tetuán. Todos los derechos reservados.',
      madeWith: 'Hecho con ❤️ en Tetuán, Marruecos',
    },
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('en');
  const t = translations[lang];

  useEffect(() => {
    document.documentElement.dir = t.dir;
    document.documentElement.lang = lang;
  }, [lang, t.dir]);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, translations }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  return useContext(LanguageContext);
}
